name: Create Resource Group

on: [push]

jobs:
  create-resource-group:
    runs-on: ubuntu-latest
    steps:
    - uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Create Resource Group
      uses: azure/CLI@v1
      with:
        azcliversion: 2.22.1
        inlineScript: |
          az group create --name my-resource-group --location eastus
